services:
  wizwiz-db:
    container_name: 'wizwiz-db'
    image: postgres:18.2-alpine
    ports:
      - '5432:5432'
    environment:
      LOG_ALL_SQL_STATEMENTS: 0
      POSTGRES_USER: wizwiz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wizwiz
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: