import { StyleSheet } from 'react-native';

import { colors } from '../../../theme';

export const styles = StyleSheet.create({
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.bg },
  scroll: { flex: 1, backgroundColor: colors.bg },
  container: { paddingBottom: 40 },
  sectionHeader: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.text,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 8,
  },
  field: {
    backgroundColor: colors.bg,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  fieldLabel: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 4,
  },
  fieldInput: {
    fontSize: 16,
    color: colors.text,
    paddingVertical: 0,
  },
  saveButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  saveButtonActive: {
    backgroundColor: colors.accent,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textMuted,
  },
  saveButtonTextActive: {
    color: colors.text,
  },
  successBanner: {
    backgroundColor: colors.successBg,
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  successText: {
    color: colors.success,
    fontSize: 15,
    fontWeight: '600',
  },
  errorBanner: {
    color: colors.error,
    backgroundColor: colors.errorBg,
    padding: 12,
    margin: 16,
    borderRadius: 8,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  modalSheet: {
    backgroundColor: colors.bg,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '70%',
    paddingTop: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
    marginBottom: 12,
  },
  modalTextInput: {
    fontSize: 18,
    color: colors.text,
    backgroundColor: colors.bgInput,
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 12,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  modalActions: {
    flexDirection: 'row',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  modalActionButton: {
    flex: 1,
    paddingVertical: 16,
    alignItems: 'center',
  },
  modalActionCancel: {
    fontSize: 16,
    color: colors.textMuted,
  },
  modalActionConfirm: {
    fontSize: 16,
    color: colors.accent,
    fontWeight: '600',
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    gap: 32,
  },
  stepperButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.bgCard,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  stepperButtonText: {
    fontSize: 28,
    color: colors.text,
    lineHeight: 34,
  },
  stepperValue: {
    fontSize: 48,
    fontWeight: '700',
    color: colors.text,
    minWidth: 60,
    textAlign: 'center',
  },
  optionRow: { paddingVertical: 14, paddingHorizontal: 24 },
  optionSelected: { backgroundColor: colors.accent },
  optionText: { fontSize: 16, color: colors.text },
  optionTextSelected: { color: colors.text, fontWeight: '600' },
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  navRowLabel: {
    fontSize: 16,
    color: colors.text,
  },
  navRowChevron: {
    fontSize: 22,
    color: colors.textMuted,
    lineHeight: 26,
  },
  cancelButton: {
    paddingVertical: 16,
    alignItems: 'center',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  cancelText: { fontSize: 16, color: colors.textMuted },
  setCurrentButton: {
    marginHorizontal: 16,
    marginTop: 24,
    paddingVertical: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bgCard,
    alignItems: 'center',
  },
  setCurrentButtonActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accent + '22',
  },
  setCurrentButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
});
