"""add_status_to_campaign

Revision ID: 770b9d375d0a
Revises: a89bde8afe4d
Create Date: 2026-04-30 22:21:16.878312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770b9d375d0a'
down_revision: Union[str, None] = 'a89bde8afe4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('status', sa.String(), nullable=False, server_default='ACTIVE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'status')
    # ### end Alembic commands ###
