"""add campaigns and dm flag

Revision ID: dfe9d49a3269
Revises: 17c4f077fcf9
Create Date: 2026-04-18 19:49:19.622931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe9d49a3269'
down_revision: Union[str, None] = '17c4f077fcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('dm_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dm_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_dm_id'), 'campaign', ['dm_id'], unique=False)
    op.create_index(op.f('ix_campaign_invite_code'), 'campaign', ['invite_code'], unique=True)
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_table('campaign_character',
    sa.Column('campaign_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('character_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'character_id')
    )
    op.add_column(
        'character',
        sa.Column('is_npc', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index(op.f('ix_character_is_npc'), 'character', ['is_npc'], unique=False)
    op.add_column(
        'user_account',
        sa.Column('is_dm', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'is_dm')
    op.drop_index(op.f('ix_character_is_npc'), table_name='character')
    op.drop_column('character', 'is_npc')
    op.drop_table('campaign_character')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_invite_code'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_dm_id'), table_name='campaign')
    op.drop_table('campaign')
    # ### end Alembic commands ###
