"""init

Revision ID: 17c4f077fcf9
Revises:
Create Date: 2026-03-14 17:32:30.343756

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17c4f077fcf9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_account_username"), "user_account", ["username"], unique=True
    )
    op.create_table(
        "character",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("character_class", sa.String(), nullable=False),
        sa.Column("species", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("experience_points", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_character_name"), "character", ["name"], unique=False)
    op.create_index(op.f("ix_character_user_id"), "character", ["user_id"], unique=False)
    op.create_table(
        "character_ability",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("character_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("ability_name", sa.String(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("modifier", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id", "ability_name", name="uq_character_ability"),
    )
    op.create_index(
        op.f("ix_character_ability_character_id"),
        "character_ability",
        ["character_id"],
        unique=False,
    )
    op.create_table(
        "character_description",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("character_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column("eye_color", sa.String(), nullable=True),
        sa.Column("hair_color", sa.String(), nullable=True),
        sa.Column("backstory", sa.String(), nullable=True),
        sa.Column("general_appearance", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_character_description_character_id"),
        "character_description",
        ["character_id"],
        unique=False,
    )
    op.create_table(
        "character_skill",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("character_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("skill_name", sa.String(), nullable=False),
        sa.Column("ability_name", sa.String(), nullable=False),
        sa.Column("proficiency_level", sa.Integer(), nullable=False),
        sa.Column("passive_score", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id", "skill_name", name="uq_character_skill"),
    )
    op.create_index(
        op.f("ix_character_skill_character_id"),
        "character_skill",
        ["character_id"],
        unique=False,
    )
    op.create_table(
        "character_update_log",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("character_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("old_values", sa.JSON(), nullable=False),
        sa.Column("new_values", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_character_update_log_character_id"),
        "character_update_log",
        ["character_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_character_update_log_character_id"), table_name="character_update_log"
    )
    op.drop_table("character_update_log")
    op.drop_index(op.f("ix_character_skill_character_id"), table_name="character_skill")
    op.drop_table("character_skill")
    op.drop_index(
        op.f("ix_character_description_character_id"), table_name="character_description"
    )
    op.drop_table("character_description")
    op.drop_index(
        op.f("ix_character_ability_character_id"), table_name="character_ability"
    )
    op.drop_table("character_ability")
    op.drop_index(op.f("ix_character_user_id"), table_name="character")
    op.drop_index(op.f("ix_character_name"), table_name="character")
    op.drop_table("character")
    op.drop_index(op.f("ix_user_account_username"), table_name="user_account")
    op.drop_table("user_account")
    # ### end Alembic commands ###
